repo:
  scanPath: ./testrepo
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: ggit
  description: hope this works
server:
  name: git.icyphox.sh
  host: 127.0.0.1
  port: 5555
ssh:
  host: 127.0.0.1
  port: 2222
  identity:
    - name: scooter
      pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJBc3G95VyLjrA2cnUjRnWRV3Uf3x08hxKkPw6ufY9YD scooter@rtw.run
