repo:
  scanPath: ./testrepo
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: ggit
  description: hope this works
server:
  name: git.icyphox.sh
  host: 127.0.0.1
  port: 5555
